# Generated by Django 6.0.7 on 2026-07-10 13:52

import django.db.models.deletion
from django.db import migrations, models

import shared.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.CharField(default=shared.models.short_uuid, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('executable', models.CharField(max_length=32)),
                ('stable_version', models.CharField(max_length=16)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PackageManager',
            fields=[
                ('id', models.CharField(default=shared.models.short_uuid, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('executable', models.CharField(max_length=32)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_managers', to='languages.language')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.CharField(default=shared.models.short_uuid, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('result', models.CharField(choices=[('init', 'Init'), ('install', 'Install'), ('add', 'Add'), ('remove', 'Remove')], max_length=16)),
                ('cmd', models.CharField(max_length=255)),
                ('package_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='languages.packagemanager')),
            ],
            options={
                'ordering': ('package_manager', 'result'),
            },
        ),
        migrations.AddConstraint(
            model_name='packagemanager',
            constraint=models.UniqueConstraint(fields=('language', 'name'), name='unique_package_manager_name_per_language'),
        ),
    ]
