import { useCallback, useEffect, useState } from 'react'
import { Alert, AppBar, Box, Breadcrumbs, Button, Card, CardActionArea, CardContent, Chip, CircularProgress, Container, CssBaseline, Dialog, DialogActions, DialogContent, DialogTitle, Grid, Link, Paper, Stack, TextField, Toolbar, Typography } from '@mui/material'
import { ActionDialog } from './ActionDialog'
import { createClient, getKey, setKey } from './api'
import type { SirenAction, SirenEntity, SirenLink } from './types'

const self = (entity: SirenEntity) => entity.links?.find(link => link.rel.includes('self'))?.href
const label = (entity: SirenEntity) => String(entity.properties?.title ?? entity.properties?.name ?? entity.properties?.slug ?? entity.properties?.id ?? entity.class?.join(' ') ?? 'Resource')

function Properties({values}: {values: Record<string, unknown>}) { return <Paper variant="outlined" sx={{p: 2}}><Grid container spacing={2}>{Object.entries(values).map(([key, value]) => <Grid key={key} size={{xs: 12, md: 6}}><Typography variant="caption" color="text.secondary">{key}</Typography><Typography sx={{whiteSpace:'pre-wrap', overflowWrap:'anywhere'}}>{typeof value === 'object' ? JSON.stringify(value, null, 2) : String(value)}</Typography></Grid>)}</Grid></Paper> }

export default function App() {
  const [entity, setEntity] = useState<SirenEntity | null>(null), [loading, setLoading] = useState(false), [error, setError] = useState(''), [keyOpen, setKeyOpen] = useState(!getKey()), [keyValue, setKeyValue] = useState(getKey()), [action, setAction] = useState<SirenAction | null>(null), [history, setHistory] = useState<{title:string; href:string}[]>([])
  const load = useCallback(async (href = new URL('/api/', location.origin).href, addHistory = true) => { setLoading(true); setError(''); try { const resource = createClient().go(href); const state = await resource.get(); const data = state.data as SirenEntity; setEntity(data); if (addHistory) setHistory(old => [...old.filter(x => x.href !== href), {title: label(data), href}].slice(-6)) } catch(e) { if (!getKey()) setKeyOpen(true); setError(e instanceof Error ? e.message : String(e)) } finally {setLoading(false)} }, [])
  useEffect(() => { if (getKey()) void load() }, [load])
  const navigate = (link: SirenLink) => void load(link.href)
  const saveKey = () => { setKey(keyValue.trim()); setKeyOpen(false); void load() }
  return <><CssBaseline/><AppBar position="sticky"><Toolbar><Typography variant="h6" sx={{flexGrow:1}}>Modwire Hypermedia Browser</Typography><Button color="inherit" onClick={() => {setKeyValue(''); setKey(''); setKeyOpen(true)}}>API key</Button></Toolbar></AppBar><Container maxWidth="xl" sx={{py:3}}><Breadcrumbs sx={{mb:2}}>{history.map(item => <Link component="button" key={item.href} onClick={() => void load(item.href, false)}>{item.title}</Link>)}</Breadcrumbs>{error && <Alert severity="error" action={<Button onClick={() => void load(self(entity ?? {}) ?? undefined)}>Retry</Button>}>{error}</Alert>}{loading ? <Box sx={{display:'grid',placeItems:'center',py:10}}><CircularProgress/></Box> : entity && <Stack spacing={3}><Box><Stack direction="row" spacing={1}>{entity.class?.map(c => <Chip key={c} label={c}/>)}</Stack><Typography variant="h3" sx={{mt:1}}>{label(entity)}</Typography></Box>{entity.properties && <Properties values={entity.properties}/>}<Stack direction="row" gap={1} flexWrap="wrap">{entity.links?.filter(l => !l.rel.includes('self')).map(link => <Button key={`${link.rel}-${link.href}`} variant="outlined" onClick={() => navigate(link)}>{link.title ?? link.rel.join(' / ')}</Button>)}</Stack>{entity.entities?.length ? <><Typography variant="h5">Items</Typography><Grid container spacing={2}>{entity.entities.map((item, i) => <Grid key={self(item) ?? i} size={{xs:12,sm:6,lg:4}}><Card variant="outlined"><CardActionArea onClick={() => self(item) && void load(self(item))}><CardContent><Typography variant="h6">{label(item)}</Typography><Typography color="text.secondary" noWrap>{item.class?.join(' · ')}</Typography></CardContent></CardActionArea></Card></Grid>)}</Grid></> : null}{entity.actions?.length ? <><Typography variant="h5">Available actions</Typography><Stack direction="row" gap={1} flexWrap="wrap">{entity.actions.map(a => <Button key={a.name} color={a.method === 'DELETE' ? 'error':'primary'} variant="contained" onClick={() => setAction(a)}>{a.title ?? a.name}</Button>)}</Stack></> : null}</Stack>}</Container><Dialog open={keyOpen}><DialogTitle>Connect to the API</DialogTitle><DialogContent><TextField autoFocus fullWidth type="password" label="API key" sx={{mt:1}} value={keyValue} onChange={e => setKeyValue(e.target.value)} onKeyDown={e => e.key === 'Enter' && saveKey()}/></DialogContent><DialogActions><Button variant="contained" disabled={!keyValue.trim()} onClick={saveKey}>Connect</Button></DialogActions></Dialog><ActionDialog action={action} onClose={() => setAction(null)} onComplete={href => {setAction(null); void load(href ?? self(entity ?? {}))}}/></>
}
