# Generated by Django 6.0.7 on 2026-07-19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlanDefinitionModel",
            fields=[
                ("identifier", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("version", models.PositiveIntegerField()),
                ("start_stage_id", models.CharField(max_length=255)),
                ("stages", models.JSONField(default=list)),
                ("transitions", models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name="PlanRunModel",
            fields=[
                ("identifier", models.UUIDField(primary_key=True, serialize=False)),
                ("definition_version", models.PositiveIntegerField()),
                ("current_stage_id", models.CharField(max_length=255)),
                ("current_input", models.JSONField(default=dict)),
                ("status", models.CharField(max_length=32)),
                ("definition", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="runs", to="plans.plandefinitionmodel")),
            ],
        ),
        migrations.CreateModel(
            name="StageSubmissionModel",
            fields=[
                ("identifier", models.UUIDField(primary_key=True, serialize=False)),
                ("stage_id", models.CharField(max_length=255)),
                ("payload", models.JSONField(default=dict)),
                ("plan_run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="submissions", to="plans.planrunmodel")),
            ],
        ),
    ]
