# Generated by Django 6.0.7 on 2026-07-19 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanDefinitionModel',
            fields=[
                ('identifier', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('version', models.PositiveIntegerField()),
                ('publication_key', models.CharField(max_length=300, unique=True)),
                ('start_stage_id', models.CharField(max_length=255)),
                ('stages', models.JSONField(default=list)),
                ('transitions', models.JSONField(default=list)),
                ('gates', models.JSONField(default=list)),
                ('operations', models.JSONField(default=list)),
                ('artifacts', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='PlanRunModel',
            fields=[
                ('identifier', models.UUIDField(primary_key=True, serialize=False)),
                ('definition_version', models.PositiveIntegerField()),
                ('current_stage_id', models.CharField(max_length=255)),
                ('current_input', models.JSONField(default=dict)),
                ('status', models.CharField(max_length=32)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='plans.plandefinitionmodel')),
            ],
        ),
        migrations.CreateModel(
            name='PlanArtifactModel',
            fields=[
                ('identifier', models.UUIDField(primary_key=True, serialize=False)),
                ('artifact_id', models.CharField(max_length=255)),
                ('artifact_key', models.CharField(max_length=300, unique=True)),
                ('payload', models.JSONField(default=dict)),
                ('plan_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='plans.planrunmodel')),
            ],
        ),
        migrations.CreateModel(
            name='OperationExecutionModel',
            fields=[
                ('identifier', models.UUIDField(primary_key=True, serialize=False)),
                ('operation_id', models.CharField(max_length=255)),
                ('execution_key', models.CharField(max_length=300, unique=True)),
                ('status', models.CharField(default='complete', max_length=32)),
                ('output', models.JSONField(default=dict)),
                ('plan_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_executions', to='plans.planrunmodel')),
            ],
        ),
        migrations.CreateModel(
            name='GateSatisfactionModel',
            fields=[
                ('identifier', models.UUIDField(primary_key=True, serialize=False)),
                ('gate_id', models.CharField(max_length=255)),
                ('satisfaction_key', models.CharField(max_length=300, unique=True)),
                ('evidence', models.JSONField(default=dict)),
                ('plan_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_satisfactions', to='plans.planrunmodel')),
            ],
        ),
        migrations.CreateModel(
            name='StageSubmissionModel',
            fields=[
                ('identifier', models.UUIDField(primary_key=True, serialize=False)),
                ('stage_id', models.CharField(max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('plan_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='plans.planrunmodel')),
            ],
        ),
    ]
