# Generated by Django 6.0.7 on 2026-07-19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("plans", "0001_initial")]

    operations = [
        migrations.AddField(model_name="plandefinitionmodel", name="gates", field=models.JSONField(default=list)),
        migrations.CreateModel(
            name="GateSatisfactionModel",
            fields=[
                ("identifier", models.UUIDField(primary_key=True, serialize=False)),
                ("gate_id", models.CharField(max_length=255)),
                ("evidence", models.JSONField(default=dict)),
                ("plan_run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="gate_satisfactions", to="plans.planrunmodel")),
            ],
        ),
    ]
