# Generated by Django 6.0.7 on 2026-07-19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("plans", "0002_stage_gates")]

    operations = [
        migrations.AddField(model_name="plandefinitionmodel", name="operations", field=models.JSONField(default=list)),
        migrations.CreateModel(
            name="OperationExecutionModel",
            fields=[
                ("identifier", models.UUIDField(primary_key=True, serialize=False)),
                ("operation_id", models.CharField(max_length=255)),
                ("output", models.JSONField(default=dict)),
                ("plan_run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="operation_executions", to="plans.planrunmodel")),
            ],
        ),
    ]
