# Generated by Django 6.0.7 on 2026-07-19 11:03

import django.db.models.deletion
from django.db import migrations, models

import modwire_agent.scaffoldings.adapters.django.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scaffolding',
            fields=[
                ('id', models.CharField(default=modwire_agent.scaffoldings.adapters.django.models.short_uuid, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('language_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(fields=('language_id', 'name'), name='unique_scaffolding_name_per_language')],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.CharField(default=modwire_agent.scaffoldings.adapters.django.models.short_uuid, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('relative_path', models.CharField(max_length=255)),
                ('file_content', models.TextField(blank=True)),
                ('write_mode', models.CharField(choices=[('managed', 'Managed'), ('create_if_missing', 'Create if missing')], default='managed', max_length=20)),
                ('scaffolding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='scaffoldings.scaffolding')),
            ],
            options={
                'ordering': ('relative_path',),
                'constraints': [models.UniqueConstraint(fields=('scaffolding', 'relative_path'), name='unique_template_path_per_scaffolding')],
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.CharField(default=modwire_agent.scaffoldings.adapters.django.models.short_uuid, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('str', 'Str'), ('int', 'Int'), ('float', 'Float'), ('bool', 'Bool'), ('list', 'List'), ('dict', 'Dict')], max_length=8)),
                ('description', models.CharField(max_length=100)),
                ('default_value', models.JSONField(blank=True, default=list)),
                ('required', models.BooleanField(default=False)),
                ('scaffolding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='scaffoldings.scaffolding')),
            ],
            options={
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(fields=('scaffolding', 'name'), name='unique_variable_name_per_scaffolding')],
            },
        ),
    ]
