# Generated by Django 6.0.7 on 2026-07-10 15:05

import django.db.models.deletion
from django.db import migrations, models

import modwire.shared.models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_command_unique_command_result_per_package_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagemanager',
            name='commit_lockfiles',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='packagemanager',
            name='lockfile_paths',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='packagemanager',
            name='manifest_paths',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='packagemanager',
            name='package_url_type',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='packagemanager',
            name='registry_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='packagemanager',
            name='supports_workspaces',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='packagemanager',
            name='version_constraint',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='command',
            name='result',
            field=models.CharField(choices=[('init', 'Init'), ('install', 'Install'), ('add_runtime', 'Add Runtime'), ('add_development', 'Add Development'), ('add_optional', 'Add Optional'), ('add_peer', 'Add Peer'), ('remove', 'Remove'), ('update', 'Update'), ('lock', 'Lock'), ('run', 'Run'), ('publish', 'Publish'), ('audit', 'Audit')], max_length=32),
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.CharField(default=modwire.shared.models.short_uuid, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('roles', models.JSONField(default=list)),
                ('executable', models.CharField(max_length=64)),
                ('package_name', models.CharField(max_length=160)),
                ('stable_version', models.CharField(default='', max_length=32)),
                ('homepage_url', models.URLField()),
                ('config_paths', models.JSONField(default=list)),
                ('default_enabled', models.BooleanField(default=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='languages.language')),
            ],
            options={
                'ordering': ('language', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ToolCommand',
            fields=[
                ('id', models.CharField(default=modwire.shared.models.short_uuid, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('capability', models.CharField(choices=[('init', 'Init'), ('check', 'Check'), ('fix', 'Fix'), ('test', 'Test'), ('coverage', 'Coverage'), ('build', 'Build'), ('serve', 'Serve'), ('audit', 'Audit')], max_length=32)),
                ('cmd', models.CharField(max_length=255)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='languages.tool')),
            ],
            options={
                'ordering': ('tool', 'capability'),
            },
        ),
        migrations.AddConstraint(
            model_name='tool',
            constraint=models.UniqueConstraint(fields=('language', 'name'), name='unique_tool_name_per_language'),
        ),
        migrations.AddConstraint(
            model_name='toolcommand',
            constraint=models.UniqueConstraint(fields=('tool', 'capability'), name='unique_command_capability_per_tool'),
        ),
    ]
