# Generated by Django 6.0.7 on 2026-07-19 11:03

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecordModel',
            fields=[
                ('identifier', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('kind', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='SectionModel',
            fields=[
                ('identifier', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('allowed_kinds', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('identifier', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContentRevisionModel',
            fields=[
                ('identifier', models.UUIDField(primary_key=True, serialize=False)),
                ('actor_id', models.CharField(default='legacy', max_length=255)),
                ('actor_kind', models.CharField(default='system', max_length=32)),
                ('markdown', models.TextField()),
                ('schema_version', models.PositiveIntegerField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_revisions', to='records.recordmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ContentProposalModel',
            fields=[
                ('identifier', models.UUIDField(primary_key=True, serialize=False)),
                ('proposed_by_id', models.CharField(max_length=255)),
                ('proposed_by_kind', models.CharField(max_length=32)),
                ('markdown', models.TextField()),
                ('status', models.CharField(max_length=32)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_proposals', to='records.recordmodel')),
            ],
        ),
        migrations.CreateModel(
            name='SectionPlacementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='records.recordmodel')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='records.sectionmodel')),
            ],
        ),
        migrations.AddField(
            model_name='recordmodel',
            name='tags',
            field=models.ManyToManyField(related_name='records', to='records.tagmodel'),
        ),
        migrations.RunPython(
            lambda apps, schema_editor: schema_editor.execute("CREATE EXTENSION IF NOT EXISTS vector") if schema_editor.connection.vendor == "postgresql" else None,
            migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name='ContentSearchProjectionModel',
            fields=[
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='search_projection', serialize=False, to='records.recordmodel')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384, null=True)),
                ('indexed_version', models.PositiveIntegerField()),
                ('revision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search_projection', to='records.contentrevisionmodel')),
            ],
        ),
    ]
