# Generated by Django 6.0.7 on 2026-07-09 21:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('slug', models.SlugField(max_length=80, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[a-z0-9]+(?:-[a-z0-9]+)*$', 'Use lowercase letters, numbers, and hyphens. Hyphens cannot be leading, trailing, or repeated.')])),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('slug', models.SlugField(max_length=80, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[a-z0-9]+(?:-[a-z0-9]+)*$', 'Use lowercase letters, numbers, and hyphens. Hyphens cannot be leading, trailing, or repeated.')])),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('search_text', models.TextField()),
                ('embedding', models.JSONField()),
                ('tags', models.ManyToManyField(related_name='sections', to='records.tag')),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('slug', models.CharField(max_length=180, primary_key=True, serialize=False)),
                ('local_slug', models.SlugField(max_length=80, validators=[django.core.validators.RegexValidator('^[a-z0-9]+(?:-[a-z0-9]+)*$', 'Use lowercase letters, numbers, and hyphens. Hyphens cannot be leading, trailing, or repeated.')])),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('sources', models.JSONField()),
                ('search_text', models.TextField()),
                ('embedding', models.JSONField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='records.section')),
                ('tags', models.ManyToManyField(related_name='records', to='records.tag')),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('position', models.PositiveIntegerField()),
                ('role', models.CharField(choices=[('heading', 'Heading'), ('subheading', 'Subheading'), ('paragraph', 'Paragraph'), ('list', 'List'), ('markdown', 'Markdown'), ('snippet', 'Snippet'), ('image', 'Image')], max_length=20)),
                ('content', models.TextField()),
                ('language', models.CharField(max_length=40)),
                ('metadata', models.JSONField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='records.record')),
            ],
            options={
                'ordering': ['record_id', 'position', 'id'],
                'constraints': [models.UniqueConstraint(fields=('record', 'position'), name='unique_record_content_position')],
            },
        ),
        migrations.AddConstraint(
            model_name='record',
            constraint=models.UniqueConstraint(fields=('section', 'local_slug'), name='unique_record_local_slug_per_section'),
        ),
    ]
