# Generated by Django 6.0.7 on 2026-07-12 01:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scaffoldings", "0002_variable_collection_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="write_mode",
            field=models.CharField(
                choices=[("managed", "Managed"), ("create_if_missing", "Create if missing")],
                default="managed",
                max_length=20,
            ),
        ),
    ]
