# Generated by Django 6.0.7 on 2026-07-12 02:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scaffoldings", "0003_template_write_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variable",
            name="default_value",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
