# Generated by Django 6.0.7 on 2026-07-12 02:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scaffoldings", "0004_alter_variable_default_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="file_content",
            field=models.TextField(blank=True),
        ),
    ]
