# Generated by Django 6.0.7 on 2026-07-19 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecordModel',
            fields=[
                ('identifier', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('kind', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='SectionModel',
            fields=[
                ('identifier', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('allowed_kinds', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('identifier', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContentRevisionModel',
            fields=[
                ('identifier', models.UUIDField(primary_key=True, serialize=False)),
                ('markdown', models.TextField()),
                ('schema_version', models.PositiveIntegerField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_revisions', to='records.recordmodel')),
            ],
        ),
        migrations.CreateModel(
            name='SectionPlacementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='records.recordmodel')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='records.sectionmodel')),
            ],
        ),
        migrations.AddField(
            model_name='recordmodel',
            name='tags',
            field=models.ManyToManyField(related_name='records', to='records.tagmodel'),
        ),
    ]
