# Generated by Django 6.0.7 on 2026-07-19 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentrevisionmodel',
            name='actor_id',
            field=models.CharField(default='legacy', max_length=255),
        ),
        migrations.AddField(
            model_name='contentrevisionmodel',
            name='actor_kind',
            field=models.CharField(default='system', max_length=32),
        ),
    ]
