# Generated by Django 6.0.7 on 2026-07-19 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_content_revision_actor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentProposalModel',
            fields=[
                ('identifier', models.UUIDField(primary_key=True, serialize=False)),
                ('proposed_by_id', models.CharField(max_length=255)),
                ('proposed_by_kind', models.CharField(max_length=32)),
                ('markdown', models.TextField()),
                ('status', models.CharField(max_length=32)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_proposals', to='records.recordmodel')),
            ],
        ),
    ]
