# Generated by Django 6.0.7 on 2026-07-19 03:28

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_content_proposal'),
    ]

    operations = [
        migrations.RunPython(
            lambda apps, schema_editor: schema_editor.execute("CREATE EXTENSION IF NOT EXISTS vector") if schema_editor.connection.vendor == "postgresql" else None,
            migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name='ContentSearchProjectionModel',
            fields=[
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='search_projection', serialize=False, to='records.recordmodel')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384, null=True)),
                ('indexed_version', models.PositiveIntegerField()),
                ('revision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search_projection', to='records.contentrevisionmodel')),
            ],
        ),
    ]
